const projects = [
  { title:'Purple Villa — Alakuko', kicker:'Completed Project', description:"A completed residential property milestone delivered through the cooperative's member property acquisition initiative.", location:'Alakuko, Lagos', status:'Completed', image:'assets/purple-villa.webp', primary:'View Project', secondary:'Property Schemes' },
  { title:'Somolu Serviced Flats', kicker:'Property Project', description:"Modern serviced apartments representing the cooperative's property investment and home-ownership opportunities for members.", location:'Somolu, Lagos', status:'Featured', image:'assets/somolu-serviced-flats.webp', primary:'View Project', secondary:'Investments' },
  { title:'Oko-Omi Land Acquisition', kicker:'Land Scheme', description:'A serviced land acquisition initiative designed to broaden long-term property ownership opportunities for cooperative members.', location:'Oko-Omi, Lagos', status:'Land Scheme', image:'assets/oko-omi-land.webp', primary:'View Project', secondary:'Contact Cooperative' }
];
const opportunities = [
  {icon:'badge-dollar-sign',tone:'purple',title:'Qwik Loans',text:'Short-term member financing for urgent needs.'},
  {icon:'chart-no-axes-combined',tone:'teal',title:'Investment Hub',text:'Member opportunities designed for long-term growth.'},
  {icon:'building-2',tone:'gold',title:'Property Projects',text:'Explore cooperative property acquisition initiatives.'},
  {icon:'piggy-bank',tone:'green',title:'Savings Plans',text:'Build financial discipline through regular savings.'}
];
const newsItems = [
  {tag:'Property Milestone',title:'Purple Villa — Alakuko',date:'Completed project',image:'assets/purple-villa.webp'},
  {tag:'Property',title:'Somolu serviced flats expand member property opportunities',date:'Featured project',image:'assets/somolu-serviced-flats.webp'},
  {tag:'Land Scheme',title:'Oko-Omi acquisition supports long-term land ownership',date:'Featured project',image:'assets/oko-omi-land.webp'},
  {tag:'Member Services',title:'Explore cooperative savings, loans and investment options',date:'Member opportunities',image:'assets/purple-villa.webp'}
];
const slidesEl=document.getElementById('heroSlides'),dotsEl=document.getElementById('heroDots'),progressEl=document.getElementById('heroProgress');let currentProject=0,heroTimer;
function refreshIcons(){if(window.lucide)window.lucide.createIcons()}
function buildHero(){slidesEl.innerHTML=projects.map((p,i)=>`<article class="hero-slide ${i===0?'active':''}"><img src="${p.image}" alt="${p.title}"><div class="hero-content"><span class="hero-kicker">${p.kicker}</span><h1>${p.title}</h1><p>${p.description}</p><div class="hero-meta"><span class="glass-chip"><i data-lucide="map-pin"></i>${p.location}</span><span class="glass-chip"><i data-lucide="badge-check"></i>${p.status}</span></div><div class="hero-actions"><a class="btn btn-primary" href="#contact">${p.primary} <span>→</span></a><a class="btn btn-gold" href="#opportunities">${p.secondary}</a></div></div></article>`).join('');dotsEl.innerHTML=projects.map((_,i)=>`<button type="button" class="${i===0?'active':''}" aria-label="Show project ${i+1}" data-index="${i}"></button>`).join('');refreshIcons()}
function restartProgress(){progressEl.classList.remove('animate');void progressEl.offsetWidth;progressEl.classList.add('animate')}
function showProject(index){currentProject=(index+projects.length)%projects.length;document.querySelectorAll('.hero-slide').forEach((el,i)=>el.classList.toggle('active',i===currentProject));dotsEl.querySelectorAll('button').forEach((el,i)=>el.classList.toggle('active',i===currentProject));restartProgress()}
function resetHeroTimer(){clearInterval(heroTimer);heroTimer=setInterval(()=>showProject(currentProject+1),5500);restartProgress()}
buildHero();showProject(0);resetHeroTimer();
document.getElementById('heroPrev').addEventListener('click',()=>{showProject(currentProject-1);resetHeroTimer()});document.getElementById('heroNext').addEventListener('click',()=>{showProject(currentProject+1);resetHeroTimer()});dotsEl.addEventListener('click',e=>{if(e.target.matches('button')){showProject(Number(e.target.dataset.index));resetHeroTimer()}});
let touchStartX=0;const hero=document.querySelector('.project-hero');hero.addEventListener('touchstart',e=>{touchStartX=e.changedTouches[0].clientX},{passive:true});hero.addEventListener('touchend',e=>{const dx=e.changedTouches[0].clientX-touchStartX;if(Math.abs(dx)>45){showProject(currentProject+(dx<0?1:-1));resetHeroTimer()}},{passive:true});hero.addEventListener('mouseenter',()=>clearInterval(heroTimer));hero.addEventListener('mouseleave',resetHeroTimer);
const opportunityList=document.getElementById('opportunityList');opportunityList.innerHTML=opportunities.map(o=>`<div class="opportunity-item"><span class="opp-icon ${o.tone}"><i data-lucide="${o.icon}"></i></span><div><h3>${o.title}</h3><p>${o.text}</p></div><a href="#contact" aria-label="View ${o.title}"><i data-lucide="chevron-right"></i></a></div>`).join('');
const newsStrip=document.getElementById('newsStrip');newsStrip.innerHTML=newsItems.map(n=>`<article class="news-card"><div class="news-thumb"><img src="${n.image}" alt=""></div><div><p class="news-tag">${n.tag}</p><h3>${n.title}</h3><p class="news-date">${n.date}</p></div></article>`).join('');
const amountInput=document.getElementById('loanAmount'),rangeInput=document.getElementById('loanRange'),termInput=document.getElementById('loanTerm'),rateInput=document.getElementById('loanRate'),monthlyEl=document.getElementById('monthlyPayment'),totalEl=document.getElementById('totalPayment'),interestEl=document.getElementById('interestPayment');
function formatNaira(n){return new Intl.NumberFormat('en-NG',{style:'currency',currency:'NGN',maximumFractionDigits:0}).format(n).replace('NGN','₦').replace(/\s/g,'')}
function calculateLoan(){const P=Math.max(0,Number(amountInput.value)||0),months=Number(termInput.value)||12,annual=Number(rateInput.value)||0,r=annual/100/12,payment=r===0?P/months:(P*r*Math.pow(1+r,months))/(Math.pow(1+r,months)-1),total=payment*months,interest=Math.max(0,total-P);monthlyEl.textContent=formatNaira(Math.round(payment));totalEl.textContent=formatNaira(Math.round(total));interestEl.textContent=formatNaira(Math.round(interest));if(Number(rangeInput.value)!==P&&P>=Number(rangeInput.min)&&P<=Number(rangeInput.max))rangeInput.value=P}
rangeInput.addEventListener('input',()=>{amountInput.value=rangeInput.value;calculateLoan()});amountInput.addEventListener('input',calculateLoan);termInput.addEventListener('change',calculateLoan);rateInput.addEventListener('change',calculateLoan);calculateLoan();
const panelToggle=document.querySelector('.panel-toggle'),calcBody=document.querySelector('.calculator-body');panelToggle.addEventListener('click',()=>{const collapsed=calcBody.classList.toggle('collapsed');panelToggle.classList.toggle('collapsed',collapsed);panelToggle.setAttribute('aria-expanded',String(!collapsed))});if(window.matchMedia('(max-width: 760px)').matches){calcBody.classList.add('collapsed');panelToggle.classList.add('collapsed');panelToggle.setAttribute('aria-expanded','false')}
const menuToggle=document.querySelector('.menu-toggle'),drawer=document.querySelector('.mobile-drawer'),overlay=document.querySelector('.drawer-overlay'),closeBtn=document.querySelector('.drawer-close');function openDrawer(){drawer.classList.add('open');overlay.classList.add('show');document.body.classList.add('no-scroll');drawer.setAttribute('aria-hidden','false');menuToggle.setAttribute('aria-expanded','true')}function closeDrawer(){drawer.classList.remove('open');overlay.classList.remove('show');document.body.classList.remove('no-scroll');drawer.setAttribute('aria-hidden','true');menuToggle.setAttribute('aria-expanded','false')}menuToggle.addEventListener('click',()=>drawer.classList.contains('open')?closeDrawer():openDrawer());closeBtn.addEventListener('click',closeDrawer);overlay.addEventListener('click',closeDrawer);document.querySelectorAll('.drawer-nav a,.drawer-actions a').forEach(a=>a.addEventListener('click',closeDrawer));
const revealObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('in-view');revealObserver.unobserve(entry.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>revealObserver.observe(el));
const statObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(!entry.isIntersecting)return;const el=entry.target,strong=el.querySelector('strong'),target=Number(el.dataset.counter);if(!strong||!Number.isFinite(target))return;if(target>500){strong.textContent=target;statObserver.unobserve(el);return}const duration=700,start=performance.now();function step(now){const pct=Math.min(1,(now-start)/duration);strong.textContent=Math.round(target*pct);if(pct<1)requestAnimationFrame(step)}requestAnimationFrame(step);statObserver.unobserve(el)}),{threshold:.45});document.querySelectorAll('[data-counter]').forEach(el=>statObserver.observe(el));
window.addEventListener('load',refreshIcons);setTimeout(refreshIcons,250);document.getElementById('year').textContent=new Date().getFullYear();
